name: Run Tests and Report Coverage

# 트리거 조건: main 브랜치에 PR 생성 시 자동 실행
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_S3_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_S3_REGION: ${{ vars.AWS_REGION }}
  AWS_S3_BUCKET: ${{ vars.AWS_BUCKET }}

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      # 1. 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2. JDK 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # 3. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # 4. 테스트 실행
      - name: Run tests
        run: ./gradlew test
      # 5. Codecov에 커버리지 업로드
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Codecov에서 발급한 토큰